NestedCommentTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NestedCommentTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: postId
        AttributeType: S
      - AttributeName: username
        AttributeType: S
      - AttributeName: commentId
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: postIdAndUsernameIndex
        KeySchema: 
          - AttributeName: postId
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: commentIdAndUsernameIndex
        KeySchema: 
          - AttributeName: commentId
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: commentIdAndCreatedAtIndex
        KeySchema: 
          - AttributeName: commentId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        Projection:
          ProjectionType: ALL