LikeTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: LikeTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: postId
        AttributeType: S
      - AttributeName: username
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: postIdAndUsernameIndex
        KeySchema: 
          - AttributeName: postId
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: postIdIndex
        KeySchema: 
          - AttributeName: postId
            KeyType: HASH
        Projection:
          ProjectionType: ALL